### PR TITLE
Add url mappings by parsing GET /mappings response and ignoring sprin…

### PR DESCRIPTION
**Pull request by ssouris**
Hi,

I managed to get it working.
I extracted a IndexToNodeConverter interface and provided two implementations the old one and the new one :).
In the Spring Container I am currently exposing only the new one.
Then I am parsing GET /mappings response and ignoring springframework beans using the "method" key in the payload.

Sadly I am not able to get the test exposeGraph passing.

Please let me know what you think :)

Thanks for your time.

### CODE REVIEW

**Comment by andreasevers** [comment]
Great @ssouris. I'll merge it with my own implementation I've been working on in the meantime.
You can expect this in the next couple of hours or tomorrow tops.

**Comment by andreasevers** [comment]
Thanks for the work you've put in this @ssouris. It was great inspiration for the eventual solution.
Please let me know if there are any things I missed out when merging your commit with mine.

Fixed in issue #4.

**Comment by ssouris** [comment]
It works really great :+1: 
Thanks for the super fast response and even faster implementation :).

Just two things from the top of my head:
- It would be nice to put a link between the microservices that are calling each other (somehow follow RestTemplate or Feign calls)
- When there are a lot of resources the dashboard becomes slow :(
- How is the UI suppose to be discovered (talking about the Node UI).

Thanks for your time :)

**Comment by andreasevers** [comment]
Glad you like it!

We thought about the things you mentioned before:
- _"It would be nice to put a link between the microservices that are calling each other (somehow follow RestTemplate or Feign calls)"_

We currently have two ways to achieve this. The first option is to create custom healthindicators on your microservice (see [this explanation](https://www.jayway.com/2014/07/22/spring-boot-custom-healthindicator/) for instance), for each microservice or whatever external node you are calling from within your microservice. The second option currently available is to use pact contracts. Such a contract describes a call between a consumer and a producer, which basically can be your microservice calling another microservice.
- _"When there are a lot of resources the dashboard becomes slow :("_

Currently the slowest aggregator call will determine the speed of the graph, added with the time it takes to fetch the eureka registry and the instances per application. The server has been rewritten to work completely with observables of rxJava, which enables us to make optimal use of the system resources. The response is sent over HTTP/1.1 though, and the response is only sent once the entire graph is constructed. Work is planned to change the frontend as well to work with Angular 2, Typescript but most importantly, rxJS as well, which allows a full reactive flow from front to back. Then hopefully a more responsive solution will be possible.
- _"How is the UI suppose to be discovered (talking about the Node UI)."_

This is currently only supported with Pacts. You can create the json contracts manually but you will still need a [pact broker](https://github.com/bethesque/pact_broker). Suggestions for other ways than pacts are more than welcome here!

**Pull request closed without merging**
